### ISSUE TITLE
web app not showing the same as in the course?

### ISSUE THREAD

**Issue by Luis-Palacios** [johnpapa/pluralsight-gulp#11]
Hello i am following the course on pluralsight and when i got to HTML injection part when you take a look at the app to make sure everything is working,  mine is not showing the same it looks like this

![preview](http://s27.postimg.org/ljoykhb2r/preview.png)

when i resize the windows:

![preview-min](http://s10.postimg.org/8ft9mhvmh/preview_min.png)

to make sure i didnt break anything i cloned the repo again and did npm install , bower install and npm start and got the same result.

all the console shows is 

Info: Primed the app data undefined
angular.js:11655 Success: Gulp Patterns Demo loaded! null
angular.js:11655 Info: Activated Dashboard undefined

but no errors, am missing something?

I am on windows 8.1

**Comment by Luis-Palacios** [comment]
ok i think i figured out by continuing the tutorial at the end of module html injection once i inserted the custom css via the gulp task the application started to work i notice the line where the custom css is:
 link rel="stylesheet" href=".tmp/styles.css"
but once injected is :  link rel="stylesheet" href="/.tmp/styles.css"/ notice the '/ the beginning'

**Comment by ghost** [comment]
I don't have the same problem, windows 7. The only thing I have, was that bootstrap has changed their main files (v3.3.5), so no css file is injected at all. You can override that in your bower.json file. Use bootstrap v3.3.4 if you don't want to override it ini your bower.json file.

**Comment by tboyce** [comment]
Run `bower install bootstrap#3.3.4 --save` to make the app use the bootstrap 3.3.4 package. That version included the bootstrap.css in the main section of the bower.json file and the latest version (3.3.5) no longer does. I am not sure how to get this working with the latest package, still learning gulp.

**Comment by pkvpraveen** [comment]
or you may add 

```
  "overrides": {
        "bootstrap": {
            "main": [
                "dist/js/bootstrap.js",
                "dist/css/bootstrap.css",
                "less/bootstrap.less"
            ]
        }
    },
```

to your bower.json file

**Comment by tamilsweet** [comment]
thanks @tboyce & @pkvpraveen for the fix :+1:

**Comment by Luis-Palacios** [comment]
Now that i've learned more about bower and wiredep , i know that both solutions from  @tboyce & @pkvpraveen works, the problem was indeed as @annabellor and @tboyce  mention about my boostsrap version no longer including the main files in the bower configuration
