### ISSUE TITLE
gulp is not set as devdependency in package.json?

### ISSUE THREAD

**Issue by cnweibo** [johnpapa/pluralsight-gulp#14]
Hi, 
according to the video, gulp should be dev dependency for npm to install.
Unfortunately, it is empty in the pacakge.json devdependancy section.
Is it a error or done intently ?

**Comment by xtreemrage** [comment]
@cnweibo Did you follow the course? When you are on module 4 - Creating a Local Package for a Project, you will install it locally.

**Comment by johnpapa** [comment]
yep
