### ISSUE TITLE
Injecting into html problem when dependencies dont specified main files

### ISSUE THREAD

**Issue by HectorLS** [johnpapa/pluralsight-gulp#25]
Everything works but there is a problem when in the example folder i figured out that Bootstrap has this in his Bower.json

``` json
"main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
```

So... they didn't add  .css as main file, instead they put the .less, and we can't inject that. They have, of course the .css file in dist/ folder.

In this case, the best is report to them right ? because change their json manually is crazy the next time you update :S

**Comment by WayneRiesterer** [comment]
Tibicenas, check this out:

https://github.com/yeoman/generator-angular/issues/965#issuecomment-68548259

You just need to add the overrides after your dependencies in the project's bower.json file (not Bootstrap's bower.json file).

:)

**Comment by HectorLS** [comment]
thanks @WayneRiesterer but the problem is that now bootstrap for example change them main files and swap .css by .less, is up to them.

Anyway this was only a course question. 
I Like Yeoman but right now have a problem with some dependency package 

``` console
UMMET PEER DEPENDENCY
```

**Comment by WayneRiesterer** [comment]
Tibicenas, are you having trouble injecting bootstrap.css using wiredep?

**Comment by WayneRiesterer** [comment]
I had the same problem. It would've worked with an earlier version of Bootstrap, but not 3.3.5.

Here is my entire bower.json file for pluralsight-gulp-master. You'll notice that I have the overrides down the bottom. I'm not sure if this is what you're after, I just thought I'd post this up before having a rest for the night.

I'm assuming that wiredep isn't loading the bootstrap.css file?

Anyway, here it is :)

```
{
  "name": "Pluralsight-Gulp",
  "version": "0.1.0",
  "description": "Starter Code for Pluralsight Course JavaScript Build Automation with Gulp.js",
  "authors": [
    "John Papa"
  ],
  "license": "MIT",
  "homepage": "https://github.com/johnpapa/pluralsight-gulp",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components"
  ],
  "devDependencies": {
    "angular-mocks": "~1.3.8",
    "sinon": "http://sinonjs.org/releases/sinon-1.12.1.js",
    "bardjs": "~0.0.3"
  },
  "dependencies": {
    "jquery": "~2.1.1",
    "angular": "~1.3.8",
    "angular-sanitize": "~1.3.8",
    "bootstrap": "~3.3.5",
    "extras.angular.plus": "~0.9.2",
    "font-awesome": "~4.2.0",
    "moment": "~2.8.4",
    "angular-ui-router": "~0.2.13",
    "toastr": "~2.1.0",
    "angular-animate": "~1.3.8"
  },
  "overrides": {
    "bootstrap": {
      "main": [
        "dist/js/bootstrap.js",
        "dist/css/bootstrap.css",
        "less/bootstrap.less"
      ]
    }
  }
}
```

**Comment by HectorLS** [comment]
Closing old issue due to inactivity
