### ISSUE TITLE
gulp-nodemon - watch not working

### ISSUE THREAD

**Issue by kevinsherman** [johnpapa/pluralsight-gulp#8]
In the "Using nodemon in a Gulp Task" segment of "Serving your Development Build", I had to change `var server = './src/server/'` to `var server = '/src/server/'` (remove the leading '.'). Not sure if this is a windows issue... but the watch wasn't firing the restart without this change.

**Comment by johnpapa** [comment]
hmmm ... let me try that again on the mac and see whats up

**Comment by johnpapa** [comment]
just tried it and it works for me on the mac. that's just odd.

**Comment by mb2o** [comment]
I'm also using Windows (v8.1) and I do not have this issue. One comment though, I would replace the value for **nodeServer** with `server + 'app.js'`

**Comment by johnpapa** [comment]
:D

**Comment by harksha** [comment]
@johnpapa I found a similar issue too on win 10. Nodemon seems to go up 2 lvls when searching for the app.js file, removing the "." didn't work for me, but switching to nodeServer:'./pluralsight-gulp/src/server/app.js' fixed it
